spring:
  application:
    name: tratic

  datasource:
    url: jdbc:postgresql://localhost:5432/tratic
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ openid, email, profile ]

          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ openid, profile_nickname ]

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com

logging:
  level:
    root: INFO
    app.leesh.tratic: DEBUG

  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{traceId:-}] [%thread] %logger{36} - %msg%n"


clients:
  upbit:
    base-url: "https://api.upbit.com/v1"
    max-candle-count-per-request: 200
  binance:
    base-url: "https://fapi.binance.com"
    max-candles-per-call: 1500
